#include(CMakeForceCompiler)
SET(CMAKE_SYSTEM_PROCESSOR ARM)
SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_PROJECT_NAME CMakeSkeleton)

SET (CMAKE_VERBOSE_MAKEFILE true )

SET(COMPILER_ROOT /bin/gcc-)

INCLUDE_DIRECTORIES( ${PROJECT_SOURCE_DIR}/include)
ADD_COMPILE_OPTIONS ( -g -Wall )
SET (CMAKE_C_FLAGS "-O" )

#USE MATH.H
LINK_LIBRARIES (-lm)
#SET (CMAKE_C_LINK_LIBRARIES "-lm")

SET(CMAKE_C_COMPILER gcc)
#SET(CMAKE_CXX_COMPILER ${COMPILER_ROOT}g++)
SET(CMAKE_ASM_COMPILER  ${COMPILER_ROOT}as)
SET(CMAKE_LINKER ${COMPILER_ROOT}ld)
SET(CMAKE_NM ${COMPILER_ROOT}nm)
SET(CMAKE_OBJCOPY ${COMPILER_ROOT}objcopy)
SET(CMAKE_OBJDUMP ${COMPILER_ROOT}objdump)
SET(CMAKE_RANLIB ${COMPILER_ROOT}ranlib)
